# Copyright (c) 2024
# Licensed under the MIT License.

"""
FastAPI server for stock prediction backtest service.

This module provides a REST API for querying stock predictions
generated by a trained Qlib model.

Endpoints:
    - GET /health: Health check
    - GET /predictions?date=YYYY-MM-DD: Get predictions for a specific date
    - GET /batch: Get predictions for a date range
    - GET /dates: Get available prediction dates
    - GET /status: Get service status
"""

import os
import logging
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Optional

from fastapi import FastAPI, HTTPException, Query, Depends, status
from fastapi.responses import JSONResponse
from fastapi.middleware.cors import CORSMiddleware
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from dotenv import load_dotenv

from .prediction_service import PredictionService
from .api_models import (
    PredictionRequest,
    PredictionResponse,
    StockPrediction,
    BatchPredictionRequest,
    BatchPredictionResponse,
    DatePrediction,
    ErrorResponse,
    HealthResponse,
)

# Load environment variables from .env file
# This will look for .env in the current directory and parent directories
load_dotenv()

# Global prediction service instance
prediction_service: Optional[PredictionService] = None

# API Token configuration
# Set API_TOKEN environment variable to enable authentication
# If not set or empty, authentication is disabled
API_TOKEN = os.getenv('API_TOKEN', '')

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Security scheme for Bearer token
security = HTTPBearer(auto_error=False)


async def verify_token(
    credentials: HTTPAuthorizationCredentials = Depends(security)
) -> bool:
    """
    Verify API token from Authorization header.

    If API_TOKEN is not set or empty, authentication is disabled.

    Args:
        credentials: HTTP Bearer credentials from Authorization header

    Raises:
        HTTPException: If token is invalid or missing

    Returns:
        True if authentication succeeds
    """
    # If no token is configured, skip authentication
    if not API_TOKEN:
        return True

    if credentials is None:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Not authenticated: Missing Authorization header",
            headers={"WWW-Authenticate": "Bearer"},
        )

    token = credentials.credentials

    if token != API_TOKEN:
        logger.warning(f"Invalid token attempt: {token[:10]}...")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid authentication token",
            headers={"WWW-Authenticate": "Bearer"},
        )

    return True


@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Lifespan context manager for startup and shutdown events.

    This replaces the deprecated on_event decorators.
    """
    global prediction_service

    # Startup
    logger.info("=" * 80)
    logger.info("STARTING BACKTEST API SERVER")
    logger.info("=" * 80)

    # Log authentication status
    if API_TOKEN:
        logger.info("🔒 Authentication ENABLED - API token is configured")
    else:
        logger.info("⚠️  Authentication DISABLED - API token not set (not recommended for production)")

    config_path = os.getenv('CONFIG_PATH', 'config/online_config.yaml')
    log_dir = os.getenv('LOG_DIR', 'data/logs')
    project_dir = os.getenv('PROJECT_DIR')

    try:
        logger.info(f"Loading prediction service with config: {config_path}")
        if project_dir:
            logger.info(f"Project directory: {project_dir}")
        prediction_service = PredictionService(
            config_path=config_path,
            log_dir=log_dir,
            project_dir=project_dir
        )
        logger.info("Prediction service loaded successfully")
    except Exception as e:
        logger.error(f"Failed to load prediction service: {e}", exc_info=True)
        # Don't raise - allow server to start in degraded mode
        prediction_service = None

    logger.info("=" * 80)
    logger.info("SERVER STARTUP COMPLETE")
    logger.info("=" * 80)

    yield

    # Shutdown
    logger.info("Shutting down server...")
    prediction_service = None
    logger.info("Server shutdown complete")


# Create FastAPI app with lifespan
app = FastAPI(
    title="Stock Prediction Backtest API",
    description="API for querying stock predictions from trained Qlib models",
    version="1.0.0",
    lifespan=lifespan
)

# Add CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Configure appropriately for production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/", tags=["Root"])
async def root():
    """Root endpoint with API information."""
    return {
        "name": "Stock Prediction Backtest API",
        "version": "1.0.0",
        "status": "running",
        "endpoints": {
            "health": "/health",
            "predictions": "/predictions",
            "batch": "/batch",
            "dates": "/dates",
            "status": "/status",
            "docs": "/docs"
        }
    }


@app.get("/health", response_model=HealthResponse, tags=["Health"])
async def health_check():
    """
    Health check endpoint.

    Returns the service status and manager information.
    """
    if prediction_service is None:
        return HealthResponse(
            status="degraded",
            manager_loaded=False,
            current_time=None,
            strategies=[]
        )

    try:
        model_info = prediction_service.get_model_info()
        return HealthResponse(
            status="healthy",
            manager_loaded=True,
            current_time=model_info.get('cur_time'),
            strategies=model_info.get('strategies', [])
        )
    except Exception as e:
        logger.error(f"Health check failed: {e}")
        return HealthResponse(
            status="unhealthy",
            manager_loaded=False,
            current_time=None,
            strategies=[]
        )


@app.get("/predictions", response_model=PredictionResponse, tags=["Predictions"])
async def get_predictions(
    date: str = Query(
        ...,
        description="Target date for prediction (format: YYYY-MM-DD)",
        examples=["2025-01-10"]
    ),
    top_n: Optional[int] = Query(
        None,
        description="Return only top N predictions",
        ge=1
    ),
    authenticated: bool = Depends(verify_token)
):
    """
    Get predictions for a specific date.

    Args:
        date: Target date in YYYY-MM-DD format
        top_n: Optional, return only top N predictions

    Returns:
        PredictionResponse with stock predictions

    Raises:
        401: Invalid or missing authentication token
        400: Invalid date format
        404: No predictions available for the date
        500: Internal server error
    """
    if prediction_service is None:
        raise HTTPException(
            status_code=503,
            detail="Prediction service not available. Check server logs."
        )

    try:
        # Get predictions
        df = prediction_service.get_predictions(date, top_n=top_n)

        # Convert to response model
        predictions = [
            StockPrediction(
                instrument=row['instrument'],
                score=float(row['score']),
                rank=int(row['rank']) if 'rank' in row and pd.notna(row['rank']) else None
            )
            for _, row in df.iterrows()
        ]

        # Prepare top_n predictions
        top_predictions = predictions[:10] if predictions else []

        return PredictionResponse(
            date=date,
            predictions=predictions,
            total_count=len(predictions),
            top_n=top_predictions  # Legacy field, always contains top 10
        )

    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except Exception as e:
        logger.error(f"Error getting predictions: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Internal server error: {str(e)}")


@app.get("/batch", response_model=BatchPredictionResponse, tags=["Predictions"])
async def get_batch_predictions(
    start_date: str = Query(
        ...,
        description="Start date (format: YYYY-MM-DD)",
        examples=["2025-01-01"]
    ),
    end_date: str = Query(
        ...,
        description="End date (format: YYYY-MM-DD)",
        examples=["2025-01-10"]
    ),
    top_n: Optional[int] = Query(
        None,
        description="Return only top N predictions per date",
        ge=1
    ),
    authenticated: bool = Depends(verify_token)
):
    """
    Get predictions for a date range.

    Args:
        start_date: Start date in YYYY-MM-DD format
        end_date: End date in YYYY-MM-DD format
        top_n: Optional, return only top N predictions per date

    Returns:
        BatchPredictionResponse with predictions for each date

    Raises:
        401: Invalid or missing authentication token
        400: Invalid date format
        500: Internal server error
    """
    if prediction_service is None:
        raise HTTPException(
            status_code=503,
            detail="Prediction service not available. Check server logs."
        )

    try:
        # Get batch predictions
        results = prediction_service.batch_get_predictions(
            start_date=start_date,
            end_date=end_date,
            top_n=top_n
        )

        # Convert to response model
        date_predictions = []
        for date, df in results.items():
            predictions = [
                StockPrediction(
                    instrument=row['instrument'],
                    score=float(row['score']),
                    rank=int(row['rank']) if 'rank' in row and pd.notna(row['rank']) else None
                )
                for _, row in df.iterrows()
            ]

            date_predictions.append(
                DatePrediction(
                    date=date,
                    predictions=predictions,
                    total_count=len(predictions)
                )
            )

        return BatchPredictionResponse(
            predictions=date_predictions,
            total_dates=len(date_predictions)
        )

    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        logger.error(f"Error getting batch predictions: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Internal server error: {str(e)}")


@app.get("/dates", tags=["Metadata"])
async def get_available_dates(authenticated: bool = Depends(verify_token)):
    """
    Get list of available prediction dates.

    Returns:
        Dict with list of dates in YYYY-MM-DD format

    Raises:
        401: Invalid or missing authentication token
    """
    if prediction_service is None:
        raise HTTPException(
            status_code=503,
            detail="Prediction service not available. Check server logs."
        )

    try:
        dates = prediction_service.get_available_dates()
        return {
            "dates": dates,
            "count": len(dates)
        }
    except Exception as e:
        logger.error(f"Error getting available dates: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Internal server error: {str(e)}")


@app.get("/status", tags=["Metadata"])
async def get_status(authenticated: bool = Depends(verify_token)):
    """
    Get detailed service status.

    Returns:
        Dict with service and manager status information

    Raises:
        401: Invalid or missing authentication token
    """
    if prediction_service is None:
        return {
            "service_status": "degraded",
            "prediction_service_loaded": False,
            "message": "Prediction service failed to load during startup"
        }

    try:
        model_info = prediction_service.get_model_info()
        available_dates = prediction_service.get_available_dates()

        return {
            "service_status": "healthy",
            "prediction_service_loaded": True,
            "manager": model_info,
            "available_dates": {
                "count": len(available_dates),
                "first": available_dates[0] if available_dates else None,
                "last": available_dates[-1] if available_dates else None
            }
        }
    except Exception as e:
        logger.error(f"Error getting status: {e}", exc_info=True)
        return {
            "service_status": "unhealthy",
            "prediction_service_loaded": True,
            "error": str(e)
        }


# Exception handlers
@app.exception_handler(ValueError)
async def value_error_handler(request, exc: ValueError):
    """Handle ValueError exceptions."""
    return JSONResponse(
        status_code=400,
        content={
            "error": "ValidationError",
            "message": str(exc)
        }
    )


@app.exception_handler(FileNotFoundError)
async def file_not_found_handler(request, exc: FileNotFoundError):
    """Handle FileNotFoundError exceptions."""
    return JSONResponse(
        status_code=404,
        content={
            "error": "FileNotFound",
            "message": str(exc)
        }
    )


# Import pandas for type checking
import pandas as pd


def main():
    """Main entry point for running the server directly."""
    import uvicorn

    # Get configuration from environment
    host = os.getenv("API_HOST", "0.0.0.0")
    port = int(os.getenv("API_PORT", "8000"))
    workers = int(os.getenv("API_WORKERS", "1"))

    logger.info(f"Starting server on {host}:{port}")

    uvicorn.run(
        "fqlib.api_server:app",
        host=host,
        port=port,
        workers=workers,
        reload=False,
        log_level="info"
    )


if __name__ == "__main__":
    main()
